name="capro-web-images"
main = "src/index.ts"
compatibility_date = "2024-10-14"
compatibility_flags = ["nodejs_compat"]
minify = true

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "capro-web-bucket"
